import streamlit as st
from fpdf import FPDF
import io

def generate_pdf(user):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Smart Agri - Farm Health Report", ln=1, align='C')
    pdf.ln(10)
    
    # Farmer Details
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Farmer Name: {user.get('name', 'N/A')}", ln=1)
    pdf.cell(200, 10, txt=f"District: {user.get('district', 'N/A')}", ln=1)
    pdf.cell(200, 10, txt="Report Date: January 2026", ln=1)
    pdf.ln(10)
    
    # Farm Status
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Farm Health Status", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="- Soil Health: Good (Nitrogen rich)", ln=1)
    pdf.cell(200, 10, txt="- Pest Risk: Low (Preventive measures active)", ln=1)
    pdf.cell(200, 10, txt="- Water Source: Well Irrigation (Sustainable)", ln=1)
    pdf.ln(10)
    
    # Credit Score
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Credit Worthiness", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="- Digi-Verified Farmer: Yes", ln=1)
    pdf.cell(200, 10, txt="- Recent Harvest: Bumper (Tomato)", ln=1)
    pdf.cell(200, 10, txt="- Community Rank: Munnodi Vivasayi", ln=1)
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(200, 10, txt="Generated by Smart Agri AI. Valid for Bank Loan Processing.", ln=1, align='C')

    return pdf.output(dest='S').encode('latin-1')

def show_documents():
    st.title("🗂️ Digital Pattayam (Document Vault)")
    st.caption("Your Alamaari for Land Records (பாதுகாப்பான பெட்டகம்)")

    c1, c2 = st.columns([2, 1])
    
    with c1:
        st.markdown("### 📄 My Documents (எனது ஆவணங்கள்)")
        
        docs = [
            {"name": "Patta Chitta (பட்டா சிட்டா)", "date": "Issued: Jan 2024", "status": "Active ✅"},
            {"name": "Crop Insurance (பயிர் காப்பீடு)", "date": "Expires: In 10 Days", "status": "Expiring ⚠️"},
            {"name": "Aadhaar Card", "date": "Verified", "status": "Active ✅"}
        ]
        
        for d in docs:
            bg = "#FFF3E0" if "Expiring" in d['status'] else "#F1F8E9"
            st.markdown(f"""
            <div style="background:{bg}; padding:15px; border-radius:10px; margin-bottom:10px; border:1px solid #ccc;">
                <div style="display:flex; justify-content:space-between;">
                    <h4 style="margin:0;">{d['name']}</h4>
                    <span>{d['status']}</span>
                </div>
                <p style="margin:5px 0; font-size:14px;">{d['date']}</p>
                <button>👁️ View</button> <button>🔗 Share</button>
            </div>
            """, unsafe_allow_html=True)
            
        st.divider()
        st.file_uploader("Upload New Document (புதிய ஆவணம்)", type=['pdf', 'jpg'])
        
    with c2:
        st.markdown("### 🔒 Security Status")
        st.success("All your documents are encrypted and safe.")
        st.markdown("---")
        
        # --- PDF Report Generation ---
        st.markdown("### 🏦 Bank Loan Report")
        st.caption("Generate your Farm Health Report for Loan Application.")
        
        if st.button("📄 Generate Report"):
            if st.session_state.get('user'):
                pdf_bytes = generate_pdf(st.session_state.user)
                st.download_button(
                    label="⬇️ Download PDF",
                    data=pdf_bytes,
                    file_name="Farm_Health_Report.pdf",
                    mime="application/pdf"
                )
            else:
                st.error("Please Login first.")
