name: AgriAI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Core API
      run: |
        cd backend_node
        docker build . -t agri-core-api:latest

    - name: Build ML Backend
      run: |
        cd backend_api
        docker build . -t agri-ml-backend:latest

    - name: Build Frontend
      run: |
        cd frontend_react
        docker build . -t agri-frontend:latest
